<a href="https://colab.research.google.com/github/dejiandrew/nba-award-predictor/blob/deji/lightgbm_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!rm *.csv
!rm *.pkl

rm: cannot remove '*.csv': No such file or directory
rm: cannot remove '*.pkl': No such file or directory

In [2]:
!gsutil -m cp -r gs://nba_award_predictor/nba_data/models/ag_models ./

Copying gs://nba_award_predictor/nba_data/models/ag_models/learner.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/metadata.json...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/CatBoost_r177_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesEntr_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/ExtraTreesGini_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMLarge_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBMXT_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/LightGBM_r131_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F1/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F2/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F3/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F4/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F5/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F6/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F7/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F8/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F1/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F2/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F3/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F4/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F5/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F6/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F7/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F8/model-internals.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetFastAI_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L1/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F3/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F4/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F5/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F6/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F7/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/S1F8/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/utils/model_template.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_BAG_L2/utils/oof.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_r79_BAG_L1/S1F1/model.pkl...
Copying gs://nba_award_predictor/nba_data/models/ag_models/models/NeuralNetTorch_r79_BAG_L1/S1F2/model.pkl...

In [3]:
!pip install wget
!pip install autogluon
!pip install lightgbm
import pandas as pd
import wget
import duckdb
import lightgbm as lgb
import joblib
import numpy as np

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=78efc9ad4c6c4f0e1ff315ccc8b633304d1ac82cfcb1d24aa013e206416d2d7c
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2
Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.16.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.6.1)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.2.2)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.42.30-py3-none-any.whl.metadata (6.8 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting ray<2.53,>=2.43.0 (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0->autogluon)
  Downloading ray-2.52.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (18.1.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (0.2.7)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (11.3.0)
Requirement already satisfied: torch<2.10,>=2.6 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.9.0+cpu)
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: transformers<4.58,>=4.51.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon) (4.57.3)
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.12.0)
Requirement already satisfied: fsspec<=2025.3 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (2025.3.0)
Collecting jsonschema<4.24,>=4.18 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: torchvision<0.25.0,>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.24.0+cpu)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.3.0)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.19.0)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.3.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (4.6.0)
Requirement already satisfied: huggingface_hub<1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (0.36.0)
Requirement already satisfied: xgboost<3.2,>=2.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.1.2)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (2.8.6)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (0.8.1)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.8.11)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (1.5.3)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading fugue-0.9.4-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (3.11.5)
Collecting chronos-forecasting<2.4,>=2.2.2 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading chronos_forecasting-2.2.2-py3-none-any.whl.metadata (23 kB)
Collecting peft<0.18,>=0.13.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (5.9.5)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (6.0.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (25.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (0.7.0)
Collecting botocore<1.43.0,>=1.42.30 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading botocore-1.42.30-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (1.17.0)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (4.0.0)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.70.16)
Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (24.1.2)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.7)
Requirement already satisfied: fastcore>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.11.2)
Requirement already satisfied: fasttransform>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.1.3)
Requirement already satisfied: plum-dispatch in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (2.6.1)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (3.1.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (3.13.3)
Collecting triad>=1.0.0 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading triad-1.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting adagio>=0.2.6 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading adagio-0.2.6-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (2.12.3)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (3.20.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (1.2.0)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (1.0.0)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (0.10.9.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.5.0->autogluon) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.30.0)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning_utilities-0.15.2-py3-none-any.whl.metadata (5.7 kB)
Collecting pytorch-lightning (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_lightning-2.6.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.9.0.post0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.60.0)
Collecting optuna (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Collecting window-ops (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading window_ops-0.0.15-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.5.0->autogluon) (5.2.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (2025.11.3)

In [4]:
wget.download('https://storage.googleapis.com/nba_award_predictor/nba_data/features-overall-weekly.csv')
features_overall_weekly_df = pd.read_csv('features-overall-weekly.csv')

In [5]:
# Remove unwanted features
features_overall_weekly_df = features_overall_weekly_df.drop(columns=['league_pts_mean', 'league_pts_std',
       'league_ast_mean', 'league_ast_std', 'league_pm_mean', 'league_pm_std',
       'z_s_pts', 'z_s_ast', 'z_s_pm'])
features_overall_weekly_df

,player_id,full_name,team,season,week,week_start,conference,pow_conference,games_played_this_week,numMinutes,...,points_mean_season,points_std_season,assists_mean_season,assists_std_season,plusMinusPoints_mean_season,plusMinusPoints_std_season,z_pts,z_ast,z_pm,breakout_score
0,305,Robert Parish,Warriors,1979,1,1979-12-31,West,West,3,101.00,...,63.000000,7.874008,8.600000,3.382307,0.000000,0.000000,-0.254000,-1.655675,0.000000,-0.623703
1,76003,Kareem Abdul-Jabbar,Lakers,1979,1,1979-12-31,West,West,2,82.00,...,105.000000,25.674890,19.400000,7.200000,0.000000,0.000000,-1.986377,-0.750000,0.000000,-1.218188
2,76005,Tom Abernethy,Warriors,1979,1,1979-12-31,West,West,1,11.00,...,22.000000,13.190906,4.750000,2.680951,0.000000,0.000000,-1.667816,-1.771759,0.000000,-1.365436
3,76011,Alvan Adams,Suns,1979,1,1979-12-31,West,West,2,64.00,...,44.200000,27.095387,13.800000,7.884161,0.000000,0.000000,-0.634794,-0.862489,0.000000,-0.576144
4,76085,James Bailey,SuperSonics,1979,1,1979-12-31,West,West,4,41.00,...,18.000000,6.745369,0.750000,0.433013,0.000000,0.000000,-0.444750,2.886751,0.000000,0.643651
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228919,1642959,Chris Youngblood,Thunder,2025,52,2025-12-22,West,West,4,11.06,...,5.000000,3.794733,1.000000,0.632456,-3.600000,10.594338,-0.527046,-1.581139,0.245414,-0.688782
228920,1642962,Drake Powell,Nets,2025,52,2025-12-22,East,East,1,17.33,...,14.142857,8.458784,4.714286,3.103652,-7.428571,13.688965,-0.844431,-0.874546,1.492339,-0.386111
228921,1642964,Brooks Barnhizer,Thunder,2025,52,2025-12-22,West,West,3,20.77,...,5.400000,2.800000,1.400000,0.489898,-9.800000,11.617229,-1.928571,1.224745,1.360049,-0.324852
228922,1643007,Taelon Peter,Pacers,2025,52,2025-12-22,East,East,4,11.26,...,3.500000,2.753785,2.166667,2.477678,-3.333333,7.866949,-0.181568,-0.874475,0.550828,-0.242961
228923,1643024,Chris Manon,Lakers,2025,52,2025-12-22,West,West,1,5.50,...,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [6]:
features_overall_weekly_df.columns

Index(['player_id', 'full_name', 'team', 'season', 'week', 'week_start',
       'conference', 'pow_conference', 'games_played_this_week', 'numMinutes',
       'points', 'assists', 'blocks', 'steals', 'reboundsTotal',
       'reboundsDefensive', 'reboundsOffensive', 'fieldGoalsAttempted',
       'fieldGoalsMade', 'threePointersAttempted', 'threePointersMade',
       'freeThrowsAttempted', 'freeThrowsMade', 'turnovers', 'foulsPersonal',
       'plusMinusPoints', 'wins_this_week', 'wins_vs_team_with_all_nba_player',
       'is_win_vs_over_500', 'opponent_has_all_nba', 'avg_opp_score',
       'avg_opp_winrate_prior', 'avg_opp_wins_prior', 'avg_opp_losses_prior',
       'away_games_prior', 'away_losses_prior', 'away_win_streak_prior',
       'away_wins_prior', 'home_games_prior', 'home_losses_prior',
       'home_win_streak_prior', 'home_wins_prior', 'losses_prior',
       'wins_vs_over_500_prior', 'won_player_of_the_week',
       'all_star_this_season', 'mvp_this_season',
       'all_nba_first_team_this_season', 'all_nba_second_team_this_season',
       'all_nba_third_team_this_season', 'team_pts', 'team_ast', 'team_blk',
       'team_stl', 'team_gms', 'pow_player_id', 'player_of_the_week',
       'fieldGoalsPercentage', 'threePointersPercentage',
       'freeThrowsPercentage', 'points_mean_season', 'points_std_season',
       'assists_mean_season', 'assists_std_season',
       'plusMinusPoints_mean_season', 'plusMinusPoints_std_season', 'z_pts',
       'z_ast', 'z_pm', 'breakout_score'],
      dtype='object')

In [7]:
query = """
WITH CTE AS (
SELECT team, season, week, SUM(assists) AS team_assists
FROM features_overall_weekly_df
GROUP BY team, season, week
)
,CTE2 AS (

SELECT team, season, week, SUM(fieldGoalsMade) AS team_fg
FROM features_overall_weekly_df
GROUP BY team, season, week
)
, CTE3 AS (
SELECT CTE.team, CTE.season, CTE.week, team_assists, team_fg
FROM CTE
JOIN CTE2
ON CTE.team = CTE2.team AND CTE.season = CTE2.season AND CTE.week = CTE2.week
)
, CTE4 AS (

SELECT team, season, week, SUM(points)/team_gms AS team_ppg
FROM features_overall_weekly_df
GROUP BY team, season, week, team_gms
)

, CTE5 AS (
SELECT *
,team_pts/team_gms AS team_ppg
FROM features_overall_weekly_df a
JOIN CTE3 b
ON a.team=b.team AND a.season = b.season AND a.week=b.week
)

, CTE6 AS (
  SELECT *,
  CASE WHEN team_ppg > 186 THEN 115 ELSE team_ppg END AS team_ppg_fixed  -- If team_ppg shows as greater than 186, set it to 115
  FROM CTE5
)

SELECT *,
AVG(team_ppg_fixed) OVER(PARTITION BY season, week) AS lg_ppg
FROM CTE6

"""
features_overall_weekly_df = duckdb.query(query).df().drop(columns=['team_1','season_1','week_1','team_ppg'])
features_overall_weekly_df

# League-wide statistics (scalars)
lg_AST = features_overall_weekly_df['assists'].mean()
lg_FG = features_overall_weekly_df['fieldGoalsMade'].mean()
lg_FT = features_overall_weekly_df['freeThrowsMade'].mean()
lg_PF = features_overall_weekly_df['foulsPersonal'].mean()
lg_FTA = features_overall_weekly_df['freeThrowsAttempted'].mean()

factor = (2/3) - (0.5 * (lg_AST / lg_FG)) / (2 * (lg_FG / lg_FT))
vop = features_overall_weekly_df['points'].mean() / (features_overall_weekly_df['fieldGoalsAttempted'].mean() - features_overall_weekly_df['reboundsOffensive'].mean() + features_overall_weekly_df['turnovers'].mean() + 0.44 * lg_FTA)
drb_pct = (features_overall_weekly_df['reboundsTotal'].mean() - features_overall_weekly_df['reboundsOffensive'].mean()) / features_overall_weekly_df['reboundsTotal'].mean()

features_overall_weekly_df['u_per'] = (1 / features_overall_weekly_df['numMinutes']) * (
    features_overall_weekly_df['threePointersMade']
    + (2/3) * features_overall_weekly_df['assists']
    + (2 - factor * (features_overall_weekly_df['team_assists'] / features_overall_weekly_df['team_fg'])) * features_overall_weekly_df['fieldGoalsMade']
    + (features_overall_weekly_df['freeThrowsMade'] * 0.5 * (1 + (1 - (features_overall_weekly_df['team_assists'] / features_overall_weekly_df['team_fg'])) + (2/3) * (features_overall_weekly_df['team_assists'] / features_overall_weekly_df['team_fg'])))
    - vop * features_overall_weekly_df['turnovers']
    - vop * drb_pct * (features_overall_weekly_df['fieldGoalsAttempted'] - features_overall_weekly_df['fieldGoalsMade'])
    - vop * 0.44 * (0.44 + (0.56 * drb_pct)) * (features_overall_weekly_df['freeThrowsAttempted'] - features_overall_weekly_df['freeThrowsMade'])
    + vop * (1 - drb_pct) * (features_overall_weekly_df['reboundsTotal'] - features_overall_weekly_df['reboundsOffensive'])
    + vop * drb_pct * features_overall_weekly_df['reboundsOffensive']
    + vop * features_overall_weekly_df['steals']
    + vop * drb_pct * features_overall_weekly_df['blocks']
    - features_overall_weekly_df['foulsPersonal'] * ((lg_FT / lg_PF) - 0.44 * (lg_FTA / lg_PF) * vop)
)

# First, check for problematic values
print("Minutes == 0:", (features_overall_weekly_df['numMinutes'] == 0).sum())
print("team_fg == 0:", (features_overall_weekly_df['team_fg'] == 0).sum())
print("NaN values in key columns:")
print(features_overall_weekly_df[['numMinutes', 'team_assists', 'team_fg']].isna().sum())

# Filter to only calculate for valid rows
valid_mask = (
    (features_overall_weekly_df['numMinutes'] > 0) &
    (features_overall_weekly_df['team_fg'] > 0) &
    features_overall_weekly_df['numMinutes'].notna()
)

# Initialize u_per with NaN
features_overall_weekly_df['u_per'] = np.nan

# Calculate only for valid rows
lg_AST = features_overall_weekly_df['assists'].mean()
lg_FG = features_overall_weekly_df['fieldGoalsMade'].mean()
lg_FT = features_overall_weekly_df['freeThrowsMade'].mean()
lg_PF = features_overall_weekly_df['foulsPersonal'].mean()
lg_FTA = features_overall_weekly_df['freeThrowsAttempted'].mean()

factor = (2/3) - (0.5 * (lg_AST / lg_FG)) / (2 * (lg_FG / lg_FT))
vop = features_overall_weekly_df['points'].mean() / (features_overall_weekly_df['fieldGoalsAttempted'].mean() - features_overall_weekly_df['reboundsOffensive'].mean() + features_overall_weekly_df['turnovers'].mean() + 0.44 * lg_FTA)
drb_pct = (features_overall_weekly_df['reboundsTotal'].mean() - features_overall_weekly_df['reboundsOffensive'].mean()) / features_overall_weekly_df['reboundsTotal'].mean()

features_overall_weekly_df.loc[valid_mask, 'u_per'] = (1 / features_overall_weekly_df.loc[valid_mask, 'numMinutes']) * (
    features_overall_weekly_df.loc[valid_mask, 'threePointersMade']
    + (2/3) * features_overall_weekly_df.loc[valid_mask, 'assists']
    + (2 - factor * (features_overall_weekly_df.loc[valid_mask, 'team_assists'] / features_overall_weekly_df.loc[valid_mask, 'team_fg'])) * features_overall_weekly_df.loc[valid_mask, 'fieldGoalsMade']
    + (features_overall_weekly_df.loc[valid_mask, 'freeThrowsMade'] * 0.5 * (1 + (1 - (features_overall_weekly_df.loc[valid_mask, 'team_assists'] / features_overall_weekly_df.loc[valid_mask, 'team_fg'])) + (2/3) * (features_overall_weekly_df.loc[valid_mask, 'team_assists'] / features_overall_weekly_df.loc[valid_mask, 'team_fg'])))
    - vop * features_overall_weekly_df.loc[valid_mask, 'turnovers']
    - vop * drb_pct * (features_overall_weekly_df.loc[valid_mask, 'fieldGoalsAttempted'] - features_overall_weekly_df.loc[valid_mask, 'fieldGoalsMade'])
    - vop * 0.44 * (0.44 + (0.56 * drb_pct)) * (features_overall_weekly_df.loc[valid_mask, 'freeThrowsAttempted'] - features_overall_weekly_df.loc[valid_mask, 'freeThrowsMade'])
    + vop * (1 - drb_pct) * (features_overall_weekly_df.loc[valid_mask, 'reboundsTotal'] - features_overall_weekly_df.loc[valid_mask, 'reboundsOffensive'])
    + vop * drb_pct * features_overall_weekly_df.loc[valid_mask, 'reboundsOffensive']
    + vop * features_overall_weekly_df.loc[valid_mask, 'steals']
    + vop * drb_pct * features_overall_weekly_df.loc[valid_mask, 'blocks']
    - features_overall_weekly_df.loc[valid_mask, 'foulsPersonal'] * ((lg_FT / lg_PF) - 0.44 * (lg_FTA / lg_PF) * vop)
)

# # Check results
# print("\nAfter filtering:")
# print("inf values:", np.isinf(features_overall_weekly_df['u_per']).sum())
# print("NaN values:", features_overall_weekly_df['u_per'].isna().sum())
# print("Valid u_per values:", valid_mask.sum())

features_overall_weekly_df['pace_adjustment'] = 2 * features_overall_weekly_df['lg_ppg'] / (features_overall_weekly_df['team_ppg_fixed'] + features_overall_weekly_df['avg_opp_score'])
features_overall_weekly_df['a_per'] = features_overall_weekly_df['pace_adjustment'] * features_overall_weekly_df['u_per']
league_avg_aPER = features_overall_weekly_df['a_per'].mean()
features_overall_weekly_df['player_efficiency_rating'] = features_overall_weekly_df['a_per'] * (15 / league_avg_aPER)

# Check final results
print("Final PER distribution:")
print(features_overall_weekly_df['player_efficiency_rating'].describe())
print()
print(f"League average PER: {features_overall_weekly_df['player_efficiency_rating'].mean():.2f} (should be ~15.0)")

# Apply minimum minutes threshold (common in PER calculations)
min_minutes = 5  # or whatever threshold makes sense for your data

features_overall_weekly_df.loc[
    features_overall_weekly_df['numMinutes'] < min_minutes,
    'player_efficiency_rating'
] = np.nan

print(f"\nAfter {min_minutes} minute filter:")
print(features_overall_weekly_df['player_efficiency_rating'].describe())

features_overall_weekly_df = features_overall_weekly_df.drop(columns=['team_assists', 'team_fg','team_ppg_fixed', 'lg_ppg', 'u_per', 'pace_adjustment', 'a_per'])
features_overall_weekly_df = features_overall_weekly_df.drop(columns=['player_efficiency_rating'])

Minutes == 0: 1236
team_fg == 0: 1
NaN values in key columns:
numMinutes      0
team_assists    0
team_fg         0
dtype: int64
Final PER distribution:
count    227687.000000
mean         15.000000
std          13.336750
min        -202.765542
25%           9.198394
50%          15.174623
75%          21.064550
max         694.720113
Name: player_efficiency_rating, dtype: float64

League average PER: 15.00 (should be ~15.0)

After 5 minute filter:
count    217907.000000
mean         15.239811
std          10.008544
min         -62.572244
25%           9.646467
50%          15.324607
75%          21.010375
max         160.347501
Name: player_efficiency_rating, dtype: float64

In [8]:
# query = """
# WITH CTE AS (
# SELECT *,
# AVG(player_efficiency_rating) OVER(PARTITION BY team, season, week) as team_avg_PER

# FROM features_overall_weekly_df
# )

# SELECT * FROM CTE

# """

# features_overall_weekly_df = duckdb.query(query).df()
# features_overall_weekly_df

In [9]:
# Only train on 2021+ seasons to account for modern scoring patterns.
#features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['season'] >= 2021]
#features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['week_start'] != '2025-12-22']
#features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['week_start'] != '2025-12-15']
# features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['week_start'] != '2025-12-08']
# features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['week_start'] != '2025-12-01']
# features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['week_start'] != '2025-11-24']
# features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['week_start'] != '2025-11-17']
# features_overall_weekly_df = features_overall_weekly_df[features_overall_weekly_df['week_start'] != '2025-11-10']

In [10]:
features_overall_weekly_df.columns

Index(['player_id', 'full_name', 'team', 'season', 'week', 'week_start',
       'conference', 'pow_conference', 'games_played_this_week', 'numMinutes',
       'points', 'assists', 'blocks', 'steals', 'reboundsTotal',
       'reboundsDefensive', 'reboundsOffensive', 'fieldGoalsAttempted',
       'fieldGoalsMade', 'threePointersAttempted', 'threePointersMade',
       'freeThrowsAttempted', 'freeThrowsMade', 'turnovers', 'foulsPersonal',
       'plusMinusPoints', 'wins_this_week', 'wins_vs_team_with_all_nba_player',
       'is_win_vs_over_500', 'opponent_has_all_nba', 'avg_opp_score',
       'avg_opp_winrate_prior', 'avg_opp_wins_prior', 'avg_opp_losses_prior',
       'away_games_prior', 'away_losses_prior', 'away_win_streak_prior',
       'away_wins_prior', 'home_games_prior', 'home_losses_prior',
       'home_win_streak_prior', 'home_wins_prior', 'losses_prior',
       'wins_vs_over_500_prior', 'won_player_of_the_week',
       'all_star_this_season', 'mvp_this_season',
       'all_nba_first_team_this_season', 'all_nba_second_team_this_season',
       'all_nba_third_team_this_season', 'team_pts', 'team_ast', 'team_blk',
       'team_stl', 'team_gms', 'pow_player_id', 'player_of_the_week',
       'fieldGoalsPercentage', 'threePointersPercentage',
       'freeThrowsPercentage', 'points_mean_season', 'points_std_season',
       'assists_mean_season', 'assists_std_season',
       'plusMinusPoints_mean_season', 'plusMinusPoints_std_season', 'z_pts',
       'z_ast', 'z_pm', 'breakout_score'],
      dtype='object')

In [11]:
# View the class imbalance (99.4% positive class, 0.6% negative class)
print(features_overall_weekly_df['won_player_of_the_week'].value_counts())
print(features_overall_weekly_df['won_player_of_the_week'].value_counts(normalize=True))

won_player_of_the_week
0    227521
1      1403
Name: count, dtype: int64
won_player_of_the_week
0    0.993871
1    0.006129
Name: proportion, dtype: float64

In [12]:
# Drop columns that contain the answer. Also drop mvp, all-star, all-nba because they are from the future when we try to do inference during season
leakage_cols = ['pow_player_id', 'player_of_the_week', 'pow_conference',
                'all_star_this_season', 'mvp_this_season',
                'all_nba_first_team_this_season', 'all_nba_second_team_this_season',
                'all_nba_third_team_this_season']

# Set aside identifier columns
id_cols = ['player_id', 'full_name', 'team', 'season', 'week', 'week_start', 'conference']

features_overall_weekly_df_clean = features_overall_weekly_df.drop(columns=leakage_cols + id_cols)
df_encoded = pd.get_dummies(features_overall_weekly_df_clean, drop_first=True)
df_encoded

,games_played_this_week,numMinutes,points,assists,blocks,steals,reboundsTotal,reboundsDefensive,reboundsOffensive,fieldGoalsAttempted,...,points_mean_season,points_std_season,assists_mean_season,assists_std_season,plusMinusPoints_mean_season,plusMinusPoints_std_season,z_pts,z_ast,z_pm,breakout_score
0,4,142.00,83.0,11.0,11.0,2.0,43.0,32.0,11.0,65.0,...,55.666667,12.666667,6.666667,3.559026,0.000000,0.000000,2.157895,1.217562,0.000000,1.444216
1,3,84.00,50.0,17.0,0.0,1.0,13.0,2.0,1.0,36.0,...,74.500000,29.111853,16.250000,7.822244,0.000000,0.000000,-0.841582,0.095880,0.000000,-0.392027
2,3,106.00,83.0,19.0,16.0,6.0,21.0,14.0,7.0,51.0,...,94.333333,25.521233,17.444444,6.075655,0.000000,0.000000,-0.444075,0.256031,0.000000,-0.145228
3,3,23.00,0.0,3.0,1.0,0.0,4.0,4.0,0.0,2.0,...,15.250000,13.917166,4.000000,2.915476,0.000000,0.000000,-1.095769,-0.342997,0.000000,-0.650784
4,3,92.00,53.0,10.0,7.0,4.0,28.0,4.0,2.0,40.0,...,43.666667,23.060307,13.777778,6.778688,0.000000,0.000000,0.404736,-0.557302,0.000000,0.035177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228919,4,11.06,3.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,5.000000,3.794733,1.000000,0.632456,-3.600000,10.594338,-0.527046,-1.581139,0.245414,-0.688782
228920,1,17.33,7.0,2.0,0.0,1.0,1.0,1.0,0.0,6.0,...,14.142857,8.458784,4.714286,3.103652,-7.428571,13.688965,-0.844431,-0.874546,1.492339,-0.386111
228921,3,20.77,0.0,2.0,0.0,0.0,3.0,3.0,0.0,3.0,...,5.400000,2.800000,1.400000,0.489898,-9.800000,11.617229,-1.928571,1.224745,1.360049,-0.324852
228922,4,11.26,3.0,0.0,0.0,0.0,2.0,0.0,2.0,3.0,...,3.500000,2.753785,2.166667,2.477678,-3.333333,7.866949,-0.181568,-0.874475,0.550828,-0.242961
228923,1,5.50,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [13]:
from sklearn.model_selection import GroupShuffleSplit

X = df_encoded.drop(columns=['won_player_of_the_week'])
y = df_encoded['won_player_of_the_week']
identifiers = features_overall_weekly_df[id_cols]

# Create groups for each season-week-conference combination
groups = (features_overall_weekly_df['season'].astype(str) + '_' +
          features_overall_weekly_df['week'].astype(str) + '_' +
          features_overall_weekly_df['conference'].astype(str))

# Use GroupShuffleSplit instead of train_test_split
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

# Split using the indices
X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]
y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]
id_train = identifiers.iloc[train_idx]
id_test = identifiers.iloc[test_idx]

print(f"Training samples: {len(X_train)}")
print(f"Test samples: {len(X_test)}")
print(f"Positive class in y_train: {100 * round(y_train.mean(),4)}%")
print(f"Positive class in y_test: {100 * round(y_test.mean(),4)}%")

Training samples: 183059
Test samples: 45865
Positive class in y_train: 0.61%
Positive class in y_test: 0.61%

In [14]:
# Train LightGBM model
lgb_model = lgb.LGBMClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    num_leaves=31,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    verbose=-1
)

# Train LightGBM model
lgb_model.fit(X_train, y_train)

# Get predictions
y_pred_proba = lgb_model.predict_proba(X_test)[:, 1]

In [15]:
evaluation_df = id_test.copy()
evaluation_df['actual_won'] = y_test.values
evaluation_df['pred_proba'] = y_pred_proba
evaluation_df

,player_id,full_name,team,season,week,week_start,conference,actual_won,pred_proba
349,229,James Edwards,Pacers,1980,47,1980-11-17,East,0,0.002069
350,305,Robert Parish,Celtics,1980,47,1980-11-17,East,0,0.066611
351,328,Rick Mahorn,Bullets,1980,47,1980-11-17,East,0,0.000197
352,940,Earl Cureton,76ers,1980,47,1980-11-17,East,0,0.000271
353,1449,Larry Bird,Celtics,1980,47,1980-11-17,East,0,0.079719
...,...,...,...,...,...,...,...,...,...
228113,1642384,Isaiah Crawford,Kings,2024,3,2025-01-13,West,0,0.000157
228114,1642403,Isaac Jones,Kings,2024,3,2025-01-13,West,0,0.000163
228115,1642419,Jamison Battle,Raptors,2024,3,2025-01-13,East,0,0.000258
228116,1642505,Alex Ducas,Thunder,2024,3,2025-01-13,West,0,0.000117
228117,1642530,Yuki Kawamura,Grizzlies,2024,3,2025-01-13,West,0,0.000230

In [16]:
actual_winners_df = evaluation_df[evaluation_df['actual_won'] == 1]
actual_winners_df.head()

,player_id,full_name,team,season,week,week_start,conference,actual_won,pred_proba
455,600014,Artis Gilmore,Bulls,1980,47,1980-11-17,East,1,0.185149
1593,78318,Isiah Thomas,Pistons,1988,10,1989-03-06,East,1,0.949387
1944,893,Michael Jordan,Bulls,1989,49,1989-12-04,East,1,0.967828
2392,431,Shawn Kemp,SuperSonics,1992,1,1993-01-04,West,1,0.591403
3182,22,Rik Smits,Pacers,1997,1,1997-12-29,East,1,0.898935

In [17]:
print(f"Total samples in evaluation_df: {len(evaluation_df)}")
print(f"Actual winners: {len(actual_winners_df)}")

Total samples in evaluation_df: 45865
Actual winners: 281

In [18]:
# How many season,conference,week combinations were there in actual_winners_df? This is our denominator for accuracy.

query = """
SELECT COUNT(DISTINCT(season,conference,week)) AS total_season_conference_weeks_we_couldve_predicted
FROM actual_winners_df
"""

total_season_conference_weeks_we_couldve_predicted = duckdb.query(query).df()['total_season_conference_weeks_we_couldve_predicted'].sum()
total_season_conference_weeks_we_couldve_predicted

np.int64(275)

In [19]:
# How many of the actual winners did we predict?
# Aka how many of the actual winners did our model assign a top-k probability for that [season,conference,week] combo?
for k in [1, 2, 3, 4, 5, 10]:
  query = f"""

  WITH Highest_Probabilities AS (
  SELECT *
  ,RANK() OVER(PARTITION BY season, conference, week ORDER BY pred_proba DESC) AS rnk
  FROM evaluation_df
  )
  ,
  Actual_Winners AS (
    SELECT * FROM evaluation_df
    WHERE actual_won = 1
  )


  SELECT * FROM Highest_Probabilities
  JOIN Actual_Winners
  ON
  Highest_Probabilities.season = Actual_Winners.season
  AND
  Highest_Probabilities.week = Actual_Winners.week
  AND
  Highest_Probabilities.conference = Actual_Winners.conference
  WHERE rnk <= {k}
  AND Highest_Probabilities.pred_proba = Actual_Winners.pred_proba
  """
  duckdb.query(query).df()
  correct_predictions_df = duckdb.query(query).df()
  total_correct_predictions = correct_predictions_df["actual_won"].sum()
  print(f"Top-{k} accuracy:", round(100*total_correct_predictions/total_season_conference_weeks_we_couldve_predicted,2),"%")

Top-1 accuracy: 55.27 %
Top-2 accuracy: 72.36 %
Top-3 accuracy: 81.82 %
Top-4 accuracy: 88.0 %
Top-5 accuracy: 93.09 %
Top-10 accuracy: 100.36 %

In [20]:
feature_importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': lgb_model.feature_importances_
}).sort_values('importance', ascending=False)

feature_importance['importance_pct'] = (feature_importance['importance'] / feature_importance['importance'].sum() * 100)

print("LightGBM Top 20 features:")
print(feature_importance.head(20)[['feature','importance_pct']])

LightGBM Top 20 features:
                        feature  importance_pct
2                        points        7.338225
36                     team_pts        5.270180
18               wins_this_week        5.236825
3                       assists        4.669780
41         fieldGoalsPercentage        4.136091
6                 reboundsTotal        3.702468
44           points_mean_season        3.435624
0        games_played_this_week        2.668446
10               fieldGoalsMade        2.668446
17              plusMinusPoints        2.535023
50                        z_pts        2.535023
46          assists_mean_season        2.434957
7             reboundsDefensive        2.401601
1                    numMinutes        2.368245
14               freeThrowsMade        2.301534
53               breakout_score        2.234823
13          freeThrowsAttempted        2.134757
51                        z_ast        1.934623
22                avg_opp_score        1.901268
48  plusMinusPoints_mean_season        1.867912

In [21]:
# import joblib

# # Save model
# joblib.dump(lgb_model, 'lightgbm_potw_model.pkl')

# # Save feature names
# joblib.dump(X_train.columns.tolist(), 'lightgbm_model_features.pkl')

In [22]:
print("\nTraining final model on 100% of data for deployment...")
final_model = lgb.LGBMClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    num_leaves=31,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    verbose=-1
)

final_model.fit(X, y)  # ALL data

# 5. Save the final model
joblib.dump(final_model, 'lightgbm_potw_model.pkl')
joblib.dump(X.columns.tolist(), 'lightgbm_model_features.pkl')

Training final model on 100% of data for deployment...

['lightgbm_model_features.pkl']

In [23]:
# Feature importance from final model
final_feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': final_model.feature_importances_
}).sort_values('importance', ascending=False)

final_feature_importance['importance_pct'] = (final_feature_importance['importance'] / final_feature_importance['importance'].sum() * 100)

print("Final Model Top 20 features:")
print(final_feature_importance.head(20)[['feature','importance_pct']])

Final Model Top 20 features:
                   feature  importance_pct
2                   points        8.475142
36                team_pts        6.006006
18          wins_this_week        5.839173
41    fieldGoalsPercentage        4.804805
3                  assists        4.637971
44      points_mean_season        4.070737
6            reboundsTotal        3.870537
46     assists_mean_season        2.936270
0   games_played_this_week        2.802803
17         plusMinusPoints        2.635969
53          breakout_score        2.535869
1               numMinutes        2.435769
10          fieldGoalsMade        2.168836
7        reboundsDefensive        2.102102
4                   blocks        2.102102
14          freeThrowsMade        2.002002
37                team_ast        1.968635
13     freeThrowsAttempted        1.835169
40                team_gms        1.801802
51                   z_ast        1.768435

**The below steps will use the above model for inference.**

In [24]:
def get_potw_predictions(week_start: str):
  """
  get_potw_predictions() does inference to predict POW.
  week_start must be a Monday in 'yyyy-mm-dd' format
  """
  import duckdb
  import joblib
  import wget

  # features-overall-weekly-for-inference.csv is calculated in a separate script that runs within the daily production pipeline
  # features-overall-weekly-for-inference.csv is needed to make predictions while the current week is in-progress (i.e. no POW announced yet)
  wget.download('https://storage.googleapis.com/nba_award_predictor/nba_data/features-overall-weekly-for-inference.csv')

  # Read in model & its feature names
  model = joblib.load('lightgbm_potw_model.pkl')
  feature_names = joblib.load('lightgbm_model_features.pkl')

  # Read in player-week stats
  overall_weekly_agg_df = pd.read_csv('features-overall-weekly-for-inference.csv')

  # Remove unwanted features
  overall_weekly_agg_df = overall_weekly_agg_df.drop(columns=['league_pts_mean', 'league_pts_std',
       'league_ast_mean', 'league_ast_std', 'league_pm_mean', 'league_pm_std',
       'z_s_pts', 'z_s_ast', 'z_s_pm'])


##############################################################
##############################################################

  query = """
  WITH CTE AS (
  SELECT team, season, week, SUM(assists) AS team_assists
  FROM overall_weekly_agg_df
  GROUP BY team, season, week
  )
  ,CTE2 AS (

  SELECT team, season, week, SUM(fieldGoalsMade) AS team_fg
  FROM overall_weekly_agg_df
  GROUP BY team, season, week
  )
  , CTE3 AS (
  SELECT CTE.team, CTE.season, CTE.week, team_assists, team_fg
  FROM CTE
  JOIN CTE2
  ON CTE.team = CTE2.team AND CTE.season = CTE2.season AND CTE.week = CTE2.week
  )
  , CTE4 AS (

  SELECT team, season, week, SUM(points)/team_gms AS team_ppg
  FROM overall_weekly_agg_df
  GROUP BY team, season, week, team_gms
  )

  , CTE5 AS (
  SELECT *
  ,team_pts/team_gms AS team_ppg
  FROM overall_weekly_agg_df a
  JOIN CTE3 b
  ON a.team=b.team AND a.season = b.season AND a.week=b.week
  )

  , CTE6 AS (
    SELECT *,
    CASE WHEN team_ppg > 186 THEN 115 ELSE team_ppg END AS team_ppg_fixed  -- If team_ppg shows as greater than 186, set it to 115
    FROM CTE5
  )

  SELECT *,
  AVG(team_ppg_fixed) OVER(PARTITION BY season, week) AS lg_ppg
  FROM CTE6

  """
  overall_weekly_agg_df = duckdb.query(query).df().drop(columns=['team_1','season_1','week_1','team_ppg'])
  overall_weekly_agg_df

  # League-wide statistics (scalars)
  lg_AST = overall_weekly_agg_df['assists'].mean()
  lg_FG = overall_weekly_agg_df['fieldGoalsMade'].mean()
  lg_FT = overall_weekly_agg_df['freeThrowsMade'].mean()
  lg_PF = overall_weekly_agg_df['foulsPersonal'].mean()
  lg_FTA = overall_weekly_agg_df['freeThrowsAttempted'].mean()

  factor = (2/3) - (0.5 * (lg_AST / lg_FG)) / (2 * (lg_FG / lg_FT))
  vop = overall_weekly_agg_df['points'].mean() / (overall_weekly_agg_df['fieldGoalsAttempted'].mean() - overall_weekly_agg_df['reboundsOffensive'].mean() + overall_weekly_agg_df['turnovers'].mean() + 0.44 * lg_FTA)
  drb_pct = (overall_weekly_agg_df['reboundsTotal'].mean() - overall_weekly_agg_df['reboundsOffensive'].mean()) / overall_weekly_agg_df['reboundsTotal'].mean()

  overall_weekly_agg_df['u_per'] = (1 / overall_weekly_agg_df['numMinutes']) * (
      overall_weekly_agg_df['threePointersMade']
      + (2/3) * overall_weekly_agg_df['assists']
      + (2 - factor * (overall_weekly_agg_df['team_assists'] / overall_weekly_agg_df['team_fg'])) * overall_weekly_agg_df['fieldGoalsMade']
      + (overall_weekly_agg_df['freeThrowsMade'] * 0.5 * (1 + (1 - (overall_weekly_agg_df['team_assists'] / overall_weekly_agg_df['team_fg'])) + (2/3) * (overall_weekly_agg_df['team_assists'] / overall_weekly_agg_df['team_fg'])))
      - vop * overall_weekly_agg_df['turnovers']
      - vop * drb_pct * (overall_weekly_agg_df['fieldGoalsAttempted'] - overall_weekly_agg_df['fieldGoalsMade'])
      - vop * 0.44 * (0.44 + (0.56 * drb_pct)) * (overall_weekly_agg_df['freeThrowsAttempted'] - overall_weekly_agg_df['freeThrowsMade'])
      + vop * (1 - drb_pct) * (overall_weekly_agg_df['reboundsTotal'] - overall_weekly_agg_df['reboundsOffensive'])
      + vop * drb_pct * overall_weekly_agg_df['reboundsOffensive']
      + vop * overall_weekly_agg_df['steals']
      + vop * drb_pct * overall_weekly_agg_df['blocks']
      - overall_weekly_agg_df['foulsPersonal'] * ((lg_FT / lg_PF) - 0.44 * (lg_FTA / lg_PF) * vop)
  )


  # Filter to only calculate for valid rows
  valid_mask = (
      (overall_weekly_agg_df['numMinutes'] > 0) &
      (overall_weekly_agg_df['team_fg'] > 0) &
      overall_weekly_agg_df['numMinutes'].notna()
  )

  # Initialize u_per with NaN
  overall_weekly_agg_df['u_per'] = np.nan

  # Calculate only for valid rows
  lg_AST = overall_weekly_agg_df['assists'].mean()
  lg_FG = overall_weekly_agg_df['fieldGoalsMade'].mean()
  lg_FT = overall_weekly_agg_df['freeThrowsMade'].mean()
  lg_PF = overall_weekly_agg_df['foulsPersonal'].mean()
  lg_FTA = overall_weekly_agg_df['freeThrowsAttempted'].mean()

  factor = (2/3) - (0.5 * (lg_AST / lg_FG)) / (2 * (lg_FG / lg_FT))
  vop = overall_weekly_agg_df['points'].mean() / (overall_weekly_agg_df['fieldGoalsAttempted'].mean() - overall_weekly_agg_df['reboundsOffensive'].mean() + overall_weekly_agg_df['turnovers'].mean() + 0.44 * lg_FTA)
  drb_pct = (overall_weekly_agg_df['reboundsTotal'].mean() - overall_weekly_agg_df['reboundsOffensive'].mean()) / overall_weekly_agg_df['reboundsTotal'].mean()

  overall_weekly_agg_df.loc[valid_mask, 'u_per'] = (1 / overall_weekly_agg_df.loc[valid_mask, 'numMinutes']) * (
      overall_weekly_agg_df.loc[valid_mask, 'threePointersMade']
      + (2/3) * overall_weekly_agg_df.loc[valid_mask, 'assists']
      + (2 - factor * (overall_weekly_agg_df.loc[valid_mask, 'team_assists'] / overall_weekly_agg_df.loc[valid_mask, 'team_fg'])) * overall_weekly_agg_df.loc[valid_mask, 'fieldGoalsMade']
      + (overall_weekly_agg_df.loc[valid_mask, 'freeThrowsMade'] * 0.5 * (1 + (1 - (overall_weekly_agg_df.loc[valid_mask, 'team_assists'] / overall_weekly_agg_df.loc[valid_mask, 'team_fg'])) + (2/3) * (overall_weekly_agg_df.loc[valid_mask, 'team_assists'] / overall_weekly_agg_df.loc[valid_mask, 'team_fg'])))
      - vop * overall_weekly_agg_df.loc[valid_mask, 'turnovers']
      - vop * drb_pct * (overall_weekly_agg_df.loc[valid_mask, 'fieldGoalsAttempted'] - overall_weekly_agg_df.loc[valid_mask, 'fieldGoalsMade'])
      - vop * 0.44 * (0.44 + (0.56 * drb_pct)) * (overall_weekly_agg_df.loc[valid_mask, 'freeThrowsAttempted'] - overall_weekly_agg_df.loc[valid_mask, 'freeThrowsMade'])
      + vop * (1 - drb_pct) * (overall_weekly_agg_df.loc[valid_mask, 'reboundsTotal'] - overall_weekly_agg_df.loc[valid_mask, 'reboundsOffensive'])
      + vop * drb_pct * overall_weekly_agg_df.loc[valid_mask, 'reboundsOffensive']
      + vop * overall_weekly_agg_df.loc[valid_mask, 'steals']
      + vop * drb_pct * overall_weekly_agg_df.loc[valid_mask, 'blocks']
      - overall_weekly_agg_df.loc[valid_mask, 'foulsPersonal'] * ((lg_FT / lg_PF) - 0.44 * (lg_FTA / lg_PF) * vop)
  )


  overall_weekly_agg_df['pace_adjustment'] = 2 * overall_weekly_agg_df['lg_ppg'] / (overall_weekly_agg_df['team_ppg_fixed'] + overall_weekly_agg_df['avg_opp_score'])
  overall_weekly_agg_df['a_per'] = overall_weekly_agg_df['pace_adjustment'] * overall_weekly_agg_df['u_per']
  league_avg_aPER = overall_weekly_agg_df['a_per'].mean()
  overall_weekly_agg_df['player_efficiency_rating'] = overall_weekly_agg_df['a_per'] * (15 / league_avg_aPER)


  # Apply minimum minutes threshold (common in PER calculations)
  min_minutes = 5  # or whatever threshold makes sense for your data

  overall_weekly_agg_df.loc[
      overall_weekly_agg_df['numMinutes'] < min_minutes,
      'player_efficiency_rating'
  ] = np.nan


  overall_weekly_agg_df = overall_weekly_agg_df.drop(columns=['team_assists', 'team_fg','team_ppg_fixed', 'lg_ppg', 'u_per', 'pace_adjustment', 'a_per'])
  overall_weekly_agg_df = overall_weekly_agg_df.drop(columns=['player_efficiency_rating'])


################################################################
################################################################

  # Query all players who played for the input week
  query = f"""
  SELECT * FROM overall_weekly_agg_df
  WHERE week_start = '{week_start}'
  """
  df = duckdb.query(query).df()

  #Keep player info separate
  player_info = df[['player_id', 'full_name', 'conference', 'season', 'week']]
  X = df[feature_names]
  probabilities = model.predict_proba(X)[:, 1]

  # Attach probabilities to the player identities
  results = player_info.copy()
  results['probability'] = probabilities

  # Now partition by season, week, and conference and return top 5 for each conference
  results
  query = f"""
  WITH CTE AS (SELECT *,
  RANK() OVER(PARTITION BY season, week, conference ORDER BY probability DESC) AS rank
  FROM results
  )

  ,CTE2 AS (
  SELECT * FROM CTE WHERE conference = 'East' AND rank <= 5
  UNION ALL
  SELECT * FROM CTE WHERE conference = 'West' AND rank <= 5

  )
  SELECT
  '{week_start}' AS week_start
  ,rank
  ,full_name as name
  ,conference
  ,probability
  FROM CTE2
  """

  top_five_per_conference = duckdb.query(query).df()

  return top_five_per_conference

get_potw_predictions('2026-01-12')

   week_start  rank               name conference  probability
0  2026-01-12     1        Bam Adebayo       East     0.925554
1  2026-01-12     2      Norman Powell       East     0.592766
2  2026-01-12     3      Pascal Siakam       East     0.259105
3  2026-01-12     4    Anfernee Simons       East     0.126771
4  2026-01-12     5       Jaylon Tyson       East     0.080397
5  2026-01-12     1       Jamal Murray       West     0.949705
6  2026-01-12     2       James Harden       West     0.923536
7  2026-01-12     3  Russell Westbrook       West     0.805186
8  2026-01-12     4  Victor Wembanyama       West     0.797603
9  2026-01-12     5     Alperen Sengun       West     0.704753

AutoGluon Model

In [25]:
def get_potw_predictions(week_start: str):
  """
  get_potw_predictions() does inference to predict POW.
  week_start must be a Monday in 'yyyy-mm-dd' format
  """
  import duckdb
  import joblib
  import wget
  import pandas as pd
  from autogluon.tabular import TabularPredictor

  # features-overall-weekly-for-inference.csv is calculated in a separate script that runs within the daily production pipeline
  # features-overall-weekly-for-inference.csv is needed to make predictions while the current week is in-progress (i.e. no POW announced yet)
  wget.download('https://storage.googleapis.com/nba_award_predictor/nba_data/features-overall-weekly-for-inference.csv')
  wget.download('https://storage.googleapis.com/nba_award_predictor/nba_data/autogluon_model_features.pkl')

  # Read in model (load the full predictor, not just the pkl)
  predictor = TabularPredictor.load('./ag_models')
  feature_names = joblib.load('autogluon_model_features.pkl')

  # Read in player-week stats
  overall_weekly_agg_df = pd.read_csv('features-overall-weekly-for-inference.csv')

  # Remove unwanted features
  overall_weekly_agg_df = overall_weekly_agg_df.drop(columns=['league_pts_mean', 'league_pts_std',
       'league_ast_mean', 'league_ast_std', 'league_pm_mean', 'league_pm_std',
       'z_s_pts', 'z_s_ast', 'z_s_pm'])

  # Query all players who played for the input week
  query = f"""
  SELECT * FROM overall_weekly_agg_df
  WHERE week_start = '{week_start}'
  """
  df = duckdb.query(query).df()

  #Keep player info separate
  player_info = df[['player_id', 'full_name', 'conference', 'season', 'week']]
  X = df[feature_names]

  # Use predictor.predict_proba instead
  probabilities = predictor.predict_proba(X)[1].values  # Get probability of class 1

  # Attach probabilities to the player identities
  results = player_info.copy()
  results['probability'] = probabilities

  # Now partition by season, week, and conference and return top 5 for each conference
  query = f"""
  WITH CTE AS (SELECT *,
  RANK() OVER(PARTITION BY season, week, conference ORDER BY probability DESC) AS rank
  FROM results
  )

  ,CTE2 AS (
  SELECT * FROM CTE WHERE conference = 'East' AND rank <= 5
  UNION ALL
  SELECT * FROM CTE WHERE conference = 'West' AND rank <= 5

  )
  SELECT
  '{week_start}' AS week_start
  ,rank
  ,full_name as name
  ,conference
  ,probability
  FROM CTE2
  """

  top_five_per_conference = duckdb.query(query).df()

  return top_five_per_conference

get_potw_predictions('2026-01-12')

   week_start  rank               name conference  probability
0  2026-01-12     1        Bam Adebayo       East     0.186792
1  2026-01-12     2      Norman Powell       East     0.041709
2  2026-01-12     3      Pascal Siakam       East     0.022399
3  2026-01-12     4   Donovan Mitchell       East     0.015891
4  2026-01-12     5        Joel Embiid       East     0.013047
5  2026-01-12     1       Jamal Murray       West     0.250329
6  2026-01-12     2       James Harden       West     0.164588
7  2026-01-12     3  Russell Westbrook       West     0.112822
8  2026-01-12     4     Alperen Sengun       West     0.097495
9  2026-01-12     5       Kevin Durant       West     0.084551

Pick out a single model from autogluon and see results e.g. "LightGBM_BAG_L1"

In [26]:
# def get_potw_predictions(week_start: str):
#   """
#   get_potw_predictions() does inference to predict POW.
#   week_start must be a Monday in 'yyyy-mm-dd' format
#   """
#   import duckdb
#   import joblib
#   import wget
#   import pandas as pd
#   from autogluon.tabular import TabularPredictor

#   # features-overall-weekly-for-inference.csv is calculated in a separate script that runs within the daily production pipeline
#   # features-overall-weekly-for-inference.csv is needed to make predictions while the current week is in-progress (i.e. no POW announced yet)
#   #wget.download('https://storage.googleapis.com/nba_award_predictor/nba_data/features-overall-weekly-for-inference.csv')
#   #wget.download('https://storage.googleapis.com/nba_award_predictor/nba_data/autogluon_model_features.pkl')

#   # Read in model (load the full predictor, not just the pkl)
#   predictor = TabularPredictor.load('./ag_models')
#   feature_names = joblib.load('autogluon_model_features.pkl')

#   # Read in player-week stats
#   overall_weekly_agg_df = pd.read_csv('features-overall-weekly-for-inference.csv')

#   # Remove unwanted features
#   overall_weekly_agg_df = overall_weekly_agg_df.drop(columns=['league_pts_mean', 'league_pts_std',
#        'league_ast_mean', 'league_ast_std', 'league_pm_mean', 'league_pm_std',
#        'z_s_pts', 'z_s_ast', 'z_s_pm'])

#   # Query all players who played for the input week
#   query = f"""
#   SELECT * FROM overall_weekly_agg_df
#   WHERE week_start = '{week_start}'
#   """
#   df = duckdb.query(query).df()

#   #Keep player info separate
#   player_info = df[['player_id', 'full_name', 'conference', 'season', 'week']]
#   X = df[feature_names]

#   # Use predictor.predict_proba with model='LightGBM_BAG_L1'
#   probabilities = predictor.predict_proba(X, model='LightGBM_BAG_L1')[1].values  # Get probability of class 1

#   # Attach probabilities to the player identities
#   results = player_info.copy()
#   results['probability'] = probabilities

#   # Now partition by season, week, and conference and return top 5 for each conference
#   query = f"""
#   WITH CTE AS (SELECT *,
#   RANK() OVER(PARTITION BY season, week, conference ORDER BY probability DESC) AS rank
#   FROM results
#   )

#   ,CTE2 AS (
#   SELECT * FROM CTE WHERE conference = 'East' AND rank <= 5
#   UNION ALL
#   SELECT * FROM CTE WHERE conference = 'West' AND rank <= 5

#   )
#   SELECT
#   '{week_start}' AS week_start
#   ,rank
#   ,full_name as name
#   ,conference
#   ,probability
#   FROM CTE2
#   """

#   top_five_per_conference = duckdb.query(query).df()

#   return top_five_per_conference

# get_potw_predictions('2025-12-15')